CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE TABLE accounts (
    subject TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE games (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INTEGER REFERENCES users(id),
    date TEXT, white TEXT, black TEXT, white_elo INTEGER, black_elo INTEGER,
    result TEXT, time_control TEXT, eco TEXT, opening TEXT, opening_ply INTEGER,
    move_count INTEGER NOT NULL, site TEXT, source TEXT NOT NULL DEFAULT 'other',
    source_url TEXT, source_game_id TEXT, pgn TEXT NOT NULL, fingerprint TEXT NOT NULL
);
CREATE UNIQUE INDEX games_owned_source_identity ON games(COALESCE(owner_user_id, 0), source, source_game_id) WHERE source_game_id IS NOT NULL;
CREATE UNIQUE INDEX games_owned_fingerprint ON games(COALESCE(owner_user_id, 0), fingerprint) WHERE fingerprint IS NOT NULL;
CREATE INDEX games_owner ON games(owner_user_id, id);
CREATE TABLE player_identities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform TEXT NOT NULL, username TEXT NOT NULL, username_normalized TEXT NOT NULL,
    UNIQUE(platform, username_normalized)
);
CREATE TABLE account_player_identities (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform TEXT NOT NULL CHECK(platform IN ('lichess', 'chess_com')),
    username TEXT NOT NULL, username_normalized TEXT NOT NULL,
    PRIMARY KEY(user_id, platform)
);
CREATE TABLE user_games (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    player_color TEXT NOT NULL CHECK(player_color IN ('white', 'black')),
    PRIMARY KEY(user_id, game_id)
);
CREATE TABLE repertoire_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    context TEXT NOT NULL, opening TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('keep', 'practice', 'try')),
    note TEXT NOT NULL DEFAULT '', UNIQUE(user_id, context, opening)
);
CREATE INDEX idx_repertoire_items_user_context ON repertoire_items(user_id, context);
CREATE TABLE practice_positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    position_key TEXT NOT NULL, fen TEXT NOT NULL, family TEXT NOT NULL,
    player_color TEXT NOT NULL CHECK(player_color IN ('white', 'black')),
    line TEXT NOT NULL, san_path TEXT NOT NULL, date_from TEXT, date_to TEXT,
    note TEXT NOT NULL DEFAULT '', candidate_move TEXT NOT NULL DEFAULT '',
    examples TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE(user_id, position_key, player_color)
);
